name: TRON CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install project dependencies
        run: npm install

      - name: Compile Contracts
        run: npx tronbox compile

      - name: Run Tests (Nile)
        run: npx tronbox test --network nile
        env:
          PRIVATE_KEY_NILE: ${{ secrets.PRIVATE_KEY_NILE }}
          FULL_NODE_NILE: ${{ secrets.FULL_NODE_NILE }}

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: |
            build
            node_modules
            contracts
            migrations
            tronbox.js
            tronbox.config.js

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-output

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # Uncomment if you need additional files from the repo that
      # aren't already in your artifact (like docs, scripts, etc.):
      # - name: Check out repository
      #   uses: actions/checkout@v2

      - name: Deploy to TRON (Nile)
        run: npx tronbox deploy --network nile
        env:
          PRIVATE_KEY_NILE: ${{ secrets.PRIVATE_KEY_NILE }}
          FULL_NODE_NILE: ${{ secrets.FULL_NODE_NILE }}
