name: TRON CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install TronBox globally
        run: npm install -g tronbox

      - name: Install project dependencies
        run: npm install

      - name: Compile Contracts
        run: tronbox compile

      - name: Run Tests
        run: tronbox test

  deploy:
    needs: build-and-test  # Deploy only after 'build-and-test' job is successful
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install TronBox globally
        run: npm install -g tronbox

      - name: Install project dependencies
        run: npm install

      - name: Deploy to TRON (nile)
        run: tronbox deploy --network nile
        env:
          PRIVATE_KEY_NILE: ${{ secrets.PRIVATE_KEY_NILE }}
          FULL_NODE_NILE: ${{ secrets.FULL_NODE_NILE }}
